### PR TITLE
Tinkering

### PR DESCRIPTION
**Pull request by discipuloosho**
first commit adjust supersu stable url for future versions of supersu.
second commit remove line from cleansystem.sh to keep print services intact.

### CODE REVIEW

**Comment by jcadduono** [comment]
at this point we could probably get away with removing the cleansystem script, what do you think @binkybear 

we use the exact url in case the next stable release has issues, we'll update the url manually once we know it's not breaking any devices

**Comment by binkybear** [comment]
@jcadduono - I agree cleansystem should be removed.  It only existed because of Nexus 7 2012 issues and we plan on dropping support for that (or only supporting CM builds).

**Comment by jcadduono** [comment]
https://github.com/offensive-security/kali-nethunter/commit/3ba6d461a429d307a665e45dccb655e381700391

**Comment by discipuloosho** [comment]
Ok. thanks to both. :) :+1:

**Comment by discipuloosho** [comment]
Although, in my device, for example, if i install the latest stock Google Factory Images and after i want install Kali Nethunter, TWRP recovery fail with: "No left space in device" (Sorry my English, always, please) and i have to delete system apps manually.
So .. I don't know what is the best option ... Perhaps you ask the user in build.sh? .. I don't know nothing  :D yourself.
Thanks for kali-nethunter, I really like to have it.

P.D.: If you decide to keep the file, that line must be deleted, please. Bye

**Pull request closed without merging**
