### PR TITLE
Update kernels.txt

### PR DESCRIPTION
**Pull request by vovanx500**
Togari kernel support :+1:

### CODE REVIEW

**Comment by vovanx500** [comment]
I was able to run nexus 5 version on my Z Ultra. 
HID Attacks and BadUSB works fine. 
Only needed to change paths in some script. Instead of "/sdcard" "/storage/emulated/0/" is required. 
I don't know if it's possible to create a config for NetHunting Building tool.

**Comment by jcadduono** [comment]
sorry i'm a bit confused on what you're trying to do.

are you trying to submit a new kernel? you will also need to add the kernel image to the nethunter-installer/kernels directory corresponding with the supported android release version, and add your device name and info to nethunter-installer/devices.cfg

you have an issue with supersu 2.68? have you reported it to Chainfire?
it seems very unlikely that supersu would need to access internal storage for any reason, are you sure this is the case?

**Comment by vovanx500** [comment]
Ok, thanks for notifying me. 
I just didn't find any specific steps on how to add a device. 
Now, I know and I will do it soon. 

Yeha, I am sure it's SuperSu, took me a while. 
If I update it to latest with recovery, I will have a boot loop. If I do the updating via "normal" way, the symlinks will break. In the root directory there is a "sdcard" which is pointing to storage/emulating/legacy. When I update SuperSU, it will become empty.

**Comment by jcadduono** [comment]
you will find complete instructions by visiting the nethunter-installer directory on github and scrolling to the readme section (or read nethunter-installer/README.md)

does it still cause your issue installing the supersu 2.68 zip by itself?

**Comment by vovanx500** [comment]
Installing zip file will cause a boot loop as well.

**Comment by jcadduono** [comment]
See continued pull request at: https://github.com/offensive-security/kali-nethunter/pull/406

**Pull request closed without merging**
