### PR TITLE
Build script windows for bacon

### PR DESCRIPTION
**Pull request by al3xv3gas**
Buildscript on windows for bacon by AL3X V3GAS

### CODE REVIEW

**Comment by jcadduono** [comment]
im gonna be honest here, this is like microwave bacon level

**Comment by al3xv3gas** [comment]
Would make things much easier though for novices to building NetHunter on a non-linux platform, like myself. And microwaved bacon tastes quite good I have to say. Merge it please. ;)

**Comment by jcadduono** [comment]
but its entirely unnecessary and the README instructions should work fine on windows already

**Comment by binkybear** [comment]
I think if it did more than the OnePlus1 I might add it but a build script should be able to handle all devices. I'm sure it would be useful to a few but for the most part Python is already in the path so the same: python build.py <-- applies.

**Comment by binkybear** [comment]
I don't mean to discourage your contributions either, feel free to continue to push anything you think might be helpful in the future.

**Comment by al3xv3gas** [comment]
Ok, point taken. I like automating every little thing lol.

**Pull request closed without merging**
