### PR TITLE
Add answers and more appropriate links to questions in the README

### PR DESCRIPTION
**Pull request by asjadsyed**
Related:

Since the wiki doesn't state which card is 'best', should the question be changed to "Which wireless cards are compatible with NetHunter?" ?
Either the question should be changed to ask which ones are compatible or the wiki should be changed to show which ones are best with NetHunter.

### CODE REVIEW

**Comment by jcadduono** [comment]
aw I was really hoping this moment wouldn't come, I really thought the current Q&A format was entertaining!

I'll fix up the wiki page to address the "which is best" question. ;)

**Comment by asjadsyed** [comment]
I thought it was a bit funny at first too but some of the answers didn't make sense (answering "Yes, ..." to a question asking "What kind of attacks..."), so I assumed it was just copy-pasted to quickly fill an answer.


Anyway, each answer I wrote was just a generic rewording essentially saying "check the wiki"
So, if you want, you can add back some humor without losing informational value:


Q: ...?
A: Yes, check our wiki for more information 

Q: ...?
A: Also on the wiki

Q: ...?
A: Still gonna be on the wiki

Q: ...?
A: Take a wild guess buddy.. Which page do you think that'll be on?

Q: ...?
A: I'll give you a hint: the answer is four letters, and those letters are w, i, k, and i.

Q: Kiwi?
A: WIKI. W-I-K-I. Like Wikipedia but just the beginning. Got it?

Q: ...?
A: I'm gonna need a new job..


Then just hyperlink each answer with the correct URLs from before

**Comment by jcadduono** [comment]
Ha, thanks for the laugh. The first changeset will work though!

**Comment by asjadsyed** [comment]
Seeing that you've added the relevant information to the wiki, I think you should now change the answer to be more accurate and informational.
I suggest changing "A list of supported devices and chipsets is on the wiki" to "This depends on your use case. More info on tradeoffs, along with a list of supported devices and chipsets is on the wiki"

In the mean time I'll close this ticket and let you directly change that however you like

**Comment by asjadsyed** [comment]
oops, didn't realize you didn't pull until I read your edit.
I've made the extra commit but I'm not sure on how to include the commit in this pull request

**Comment by asjadsyed** [comment]
You can close this now (I no longer have permission to close my own pull request thread it seems)

**Pull request merged**
