### PR TITLE
New AK kernel for CM12.1

### PR DESCRIPTION
**Pull request by l0rdg3x**

### CODE REVIEW

**Comment by binkybear** [comment]
@l0rdg3x - Have you tested the AK kernel? The only reason I would hesitate is that I don't believe the factory images are up to 12.1 yet.  But I wouldn't mind testing this before I merged.

**Comment by l0rdg3x** [comment]
Yes, i have tested it.

**Comment by l0rdg3x** [comment]
I think there is something wrong with y-cable patches. My Y-Cable see External USB wifi device but phone don't charge.

**Comment by binkybear** [comment]
@l0rdg3x - I've been working on ycable a little bit and here are two patches that have semi-worked for me:

https://github.com/binkybear/AK-OnePone/commit/02c00395177028b914ea437ff4515937d52c3791
https://github.com/binkybear/AK-OnePone/commit/fda96c90c3bae120c24415fb7aa15b21fbd1a2db

Did you try those ones are the ones from previous msm devices (n7 2013/n5).  The ones from the previous device use a different charger.

Currently the ycable patch (above) will hold a charge but will not increase the charge and will not show up as charging.  But it will maintain the charge.

**Comment by jmingov** [comment]
Hey, l0rdg3x

> but phone don't charge

It Is really not getting powered or its just the icon not changing?

---------

Can you come to the IRC chanell #nethunter so we can talk?


Jaime

**Comment by l0rdg3x** [comment]
In these days I'm short of time due to school exams, I've quickly tested
the y-cable only for few minutes.
 Il 20/giu/2015 15:35, "3boll" <notifications@github.com> ha scritto:

**Comment by binkybear** [comment]
I tested this out on the latest CM12S and it bootlooped for me.  Did you test it out on the CM nightlies?

**Comment by l0rdg3x** [comment]
I tested it on cm12.1 nightly

**Comment by binkybear** [comment]
l0rdg3x - Have you had a chance to test latest kernel?  I believe I fixed wlan1 disconnect issue.

**Comment by l0rdg3x** [comment]
Yes i can.

**Comment by l0rdg3x** [comment]
I have tested your kernel (check your repo for my pull request) on COS 12.1- YOG4PAS1N0 and......

All work(wlan usb device found, usb keyboard, nethunter app) and device don't reboot when remove wlan usb device :dancer: 
Awesome work Binky.

**Comment by l0rdg3x** [comment]
Only a little problem charging through Y-Cable don't work.

**Comment by binkybear** [comment]
Yes it uses a qpnp-charger.c which is a bit different then the other msm devices.  That's next on my list to figure out.

**Pull request closed without merging**
