### PR TITLE
Again some improvements

### PR DESCRIPTION
**Pull request by zanezam**
I got problems with apps not installed or not able to be re-/installed after updating
the install package so this would be a solution to avoid such problems.
second commit is self-explaining :-)

### CODE REVIEW

**Comment by binkybear** [comment]
Looks good to me.  @jcadduono, I'll let you look it over since it's for installer.

**Comment by jcadduono** [comment]
I'll shorten it up a little before committing there might be a little simpler way to go about it.
@binkybear this might not be place to ask but why are we including BusyBox app in the new installer when 100% of cases of missing BusyBox is due to users updating nethunter app after using old installer o.O

**Comment by binkybear** [comment]
@jcadduono - I think it has more to do with people installing their own version of busybox over ours  or not wanting to upgrade (then running into issues).  It's more preventative.  But we don't NEED to include it.

**Comment by jcadduono** [comment]
@binkybear they can't though, we call ours busybox_nh and create a symlink called busybox if it doesnt exist, and every command used by the app is prefixed by whichBusybox which always calls busybox_nh if it exists

**Comment by binkybear** [comment]
You are correct, I didn't think about that.  We can remove it.

**Comment by jcadduono** [comment]
What do you think, @zanezam : https://github.com/offensive-security/kali-nethunter/commit/4b9ab28efb7355b9767ebca48bd0120db95995d1

**Comment by zanezam** [comment]
i think thats very good and a bit more of a "flexible loopish" solution than my straight one :-)
fine fine will give it a try when i have time but im confident that this will do the right things.
thx for adding this!

**Comment by jcadduono** [comment]
i need to start remembering that for -> if then is silly.
i should have went with for -> [ condition not to link ] || continue

**Pull request closed without merging**
