### PR TITLE
Update NH-galaxy a5

### PR DESCRIPTION
**Pull request by DeadSquirrel01**
Added support for usb bluetooth dongles and added related kernel modules

### CODE REVIEW

**Comment by jcadduono** [comment]
you need to rebase!!!

**Comment by DeadSquirrel01** [comment]
sorry I forgot to do it :D

**Comment by DeadSquirrel01** [comment]
Now I've a question :D, do I need other patches, except mac8021, HID patch and cdrom patch ? Thanks in advance :)

**Comment by DeadSquirrel01** [comment]
Sorry I've accidentally closed pull request when I wanted to add comment ;)

**Comment by DeadSquirrel01** [comment]
Now there is only one clean commit :D

**Comment by jcadduono** [comment]
looks good, can u just update your commit message to include the device, ex.
`git commit --amend -m "[Galaxy A5 (2015)] Add support for USB Bluetooth Dongles"`

**Comment by DeadSquirrel01** [comment]
Sure, now I'll redownload the fork, because I deleted it due to a chroot problem (I've deleted it when testing this new build and I forgot to move the fork :D

**Comment by DeadSquirrel01** [comment]
All done
PS (can u replace nutella with nougat on build.py :P)

**Comment by jcadduono** [comment]
i thought i got all references of it? i cant find nutella anywhere

**Comment by DeadSquirrel01** [comment]
I saw it on build.py line 439 but maybe it's because I have unupdated repo

**Pull request merged**
