### PR TITLE
New Device: Samsung Galaxy A5

### PR DESCRIPTION
**Pull request by DeadSquirrel01**
If you need kernel config, i've uploaded it here:
https://www.androidfilehost.com/?fid=24580943222146797
I've uploaded kernel modules too (it's a flashable zip) here:
https://www.androidfilehost.com/?fid=24580943222146445
I hope you appreciate my work :)

### CODE REVIEW

**Comment by darkownah** [comment]
Can you make it for Note 4 ? :)

**Comment by DeadSquirrel01** [comment]
I can make it, but I can't test it, because i haven't got that phone

**Comment by darkownah** [comment]
send me the kernel, i test it.

**Comment by DeadSquirrel01** [comment]
Ok, what is you e-mail?

**Comment by darkownah** [comment]
derfewi008@web.de

**Comment by binkybear** [comment]
@DeadSquirrel01 Do you have zImage also?  Right now you just have a link to your kernel github rep (and you mispelled author).  Even if I merge this nobody would be able to flash anything.  You need to create a folder in the lollipop or marshmallow folder called a5ulte.  Then add  a zImage or zImage-dtb (or whatever is outputted).

**Comment by DeadSquirrel01** [comment]
now i added zImage (sorry, i forgot to add email to git config)

**Comment by jcadduono** [comment]
can you flatten your commits and then rebase them on master?
to do this:
```sh
git remote add ofsc https://github.com/offensive-security/kali-nethunter.git
git fetch ofsc
git rebase -i HEAD~5
# change pick to fix on all your commits AFTER your initial one, then save.
# this will flatten those extra commits down into your first one, making one clean commit
git rebase ofsc/master
# this will put your single commit on top of our latest sources so we can merge it
# you may need to fix conflicts when doing this
git push -f
# you will need to force push to your own repo, this is necessary with rebases
```

**Comment by DeadSquirrel01** [comment]
Fixed :) now there are two commits

**Comment by jcadduono** [comment]
I've fixed up your commits and recommitted them.
For future reference, you should always look at what your changes are doing before pushing them.
You can use `git show HEAD` to see what changes you've made.
Also, be careful not to rebase into someone else's commit!
Interactive rebasing allows you to change the order and squash your commits together, but just be sure no one elses is being affected by this.

**Pull request merged**
