### PR TITLE
Jfltexx

### PR DESCRIPTION
**Pull request by semsevens**
New device: Samsung Galaxy S4 (jfltexx) support

### CODE REVIEW

**Comment by binkybear** [comment]
Looks good but only problem I see is there is an Image and Zimage.  Do you need both?

**Comment by jcadduono** [comment]
Hey, glad you decided to work on this device and submit it!
Just a few things:
You don't need to declare arch if it is armhf in devices.cfg as that is the default
You don't need to declare kernel name as NetHunter kernel either as that is also the default

You should separate your changes into multiple commits and give them meaningful names in your kernel repository.
I was going over your 1 commit and noticed you had reject files in there. They should be cleaned up after you've fixed mismerges.

Any reason in particular that you removed this line?
https://github.com/semsevens/nethunter_kernel_jfltexx/commit/20e1e7ba4981e650ec181f0520aba0e5a95de5e7#diff-ca319ad4a1247177c7c71833f4f6adcfL914
(it abruptly ends most of the function now)

Another small thing, you're using a generic arm-eabi toolchain. This will probably reduce the performance of the kernel somewhat over an eabihf toolchain. You may want to consider using something more recent and capable of krait architecture optimizations if you're able to fix a few minor code issues it detects, such as:
https://releases.linaro.org/components/toolchain/binaries/4.9-2016.02/arm-linux-gnueabihf/gcc-linaro-4.9-2016.02-x86_64_arm-linux-gnueabihf.tar.xz

Missing kernel config items (you can simply copy and paste this at the bottom of your defconfig and rerun menuconfig:
CONFIG_FHANDLE=y
CONFIG_EXPORTFS=y
CONFIG_LOCALVERSION="-nethunter-jfltexx"

You can remove:
CONFIG_F2FS_FS_POSIX_ACL (ACL not used by Android)

Since you are supporting f2fs in your kernel, you could consider adding a file like this:
https://github.com/offensive-security/kali-nethunter/blob/master/nethunter-installer/kernels/marshmallow/hltecan/patch.d/05-f2fs-fstab
to your device, which automatically adds f2fs to the fstab if it isn't there already. (I haven't checked jflte CM to know if it already has it or not)

Keep up the good work!

**Comment by semsevens** [comment]
@jcadduono 
Thanks for your advice. I have taken all your advice.
It's my first time compiling kernel.  
If there is something wrong , please exhibitions.

**Comment by jcadduono** [comment]
your config is gone now

**Comment by semsevens** [comment]
You mean the file ".config" ?

**Comment by jcadduono** [comment]
updated previous comment

**Comment by semsevens** [comment]
My previous "kali_defconfig" is a full config.
But when I `make kali_defconfig`, it generates the `.config` which is different with 
"kali_defconfig".
So, I copy the "kali_defconfig" to ".config".
Then, I `make savedefconfig && cp defconfig arch/arm/configs/kali_defconfig`.
After that, I `make kali_defconfig`, the ".config" file is now well.
So, as you say, the "kali_defconfig" is a base config  now.

**Comment by jcadduono** [comment]
that's really confusing why not just use full defconfig @ kali_defconfig

**Comment by semsevens** [comment]
Yeah, I have restored the "kali_defconfig" to a full defconfig.

**Pull request merged**
