### PR TITLE
Comment out sleeps for windows 7, removed unnecessary comments.

### PR DESCRIPTION
**Pull request by Mr0x58**
The 1 sec sleep is too long, makes the HID attack not so stealthy. 
I only commented out the parts I tested with unknownpwn and it seems to work just fine.

I don't have a windows 8 on hand to try out the rest.

### CODE REVIEW

**Comment by cquick97** [comment]
For older (slower) win7 machines, the sleeps are necessary. I've tested, I need them for it to work on my test boxes at least. Win8 didn't need them though.

**Comment by offensive-security** [comment]
Yes, timing on these things in finicky, as a slower, burdened machine needs these pauses. I'm thinking of making the sleep length a variable which has a 1 second value default...which can be changed.

**Comment by cquick97** [comment]
Actually, looking back I had never changed anything in keyseed, I had changed hid-all.py, so it may work. I don't have a box to test on at the moment.

**Comment by unknownpwn** [comment]
A variable sounds good! I tried reducing the delays here and there but need to test it a bit more before doing a pr, but it seems to work fine on a windows 8 vm with one processor and one gig ram.

**Comment by Mr0x58** [comment]
okay, I might have jumped the ship too quickly after my initial tests. Going to test more. Tho' the useless code could still be removed.

**Pull request closed without merging**
