### PR TITLE
Some useful things?

### PR DESCRIPTION
**Pull request by zanezam**
at least things to make my personal live a bit easier, maybe something for everyone?
anyway would be nice to see some of it in the master branch. thx for checking.

### CODE REVIEW

**Comment by jcadduono** [comment]
bit confused what do you mean it exits the loop on first? why would you loop through ignored items?

**Comment by zanezam** [comment]
hi jcadduono,
oh  yes i was also confused. that drove me a bit nuts as i'm not a python specialist *g* anyway the thing is the loop breaks out after hitting the first exclusion from IgnoredFiles in the current dir. if u want to exclude something in addition in the same directory  u can't because next subdirectory comes in place after break out the loop. as u can see in my case i wanted to exclude the wallpaper directory but then suddenly 'arch' didn't get excluded anymore. wallpaper was just the first hit in the dir now so that dir was done arch stayed. which one stays and which one gets deleted is a matter of sequence but still u only can exclude one dir/file per dir. hence i thought about looping through all values in the ignored list to really catch all (probably multiple things) in one dir BEFORE going to next dir helps, did that and actually that fixed my problem.

**Comment by jcadduono** [comment]
sounds like a bug with your python, i cant reproduce it, what i can reproduce however is the IgnoredFiles appends in the wrong area of build.py, so they are getting ignored after boot-patcher is prepared, causing freespace.sh to not be ignored there, so moved them up a bit.

**Comment by zanezam** [comment]
strange though but yeah might be a bug on my side somehow i had the feeling that this is just a "workaround" as everything in these loops really looks good in my "humble not python trained eyes" so i have to check what's the real cause here on my system. anyway thx for adding the rest!

**Comment by zanezam** [comment]
ok me again and confused again: i have to ask why i should pull request in the device tree when the folder is in this repo in boot-patcher/ramdisk-patch? beside of that the scripts are ment to be for all kernels so they would apply in general. did i miss or misunderstand something?

**Comment by jcadduono** [comment]
they're only useful on a few of the kernels maybe. most of the time we don't use modules, they are already built in and do not need to be loaded, making the scripts pointless to execute.
if the kernel actually uses modules, they will be located in thedevice/modules folder, and if you don't see ath/ralink/rtl modules in there then they are built in and already enabled as well, so don't need them there either.

**Comment by zanezam** [comment]
about the scripts: aye i see good point that not all kernel have the modules (even though they should if one does the changes according to the documentation) but still my tests showed things in your mentioned directory in the device tree don't get included then as there is no handling in the installation script yet (or i miss something), only stuff from boot-patcher/ramdisk-patch gets included. anyway i agree and i'll do the encouraged device specific pull request.

and again yes that's really strange i also see no point why it should'nt work properly (hence drove me nuts) ehm yes i'm very sure that "arch" gets included when wallpaper gets excluded at the same time according to this (and also manually checked every time in the zip file):
```
for example command
/build.py -d oneplus1 -m -nk -ns -nb -nf

makes this:
Found SuperSU zip at: update/supersu.zip
Extracting x86/supolicy to boot-patcher/arch/i386/system/xbin/supolicy
Extracting x86/libsupol.so to boot-patcher/arch/i386/system/lib/libsupol.so
Extracting arm64/supolicy to boot-patcher/arch/arm64/system/xbin/supolicy
Extracting arm64/libsupol.so to boot-patcher/arch/arm64/system/lib64/libsupol.so
Extracting armv7/supolicy to boot-patcher/arch/armhf/system/xbin/supolicy
Extracting armv7/libsupol.so to boot-patcher/arch/armhf/system/lib/libsupol.so
Extracting x64/supolicy to boot-patcher/arch/amd64/system/xbin/supolicy
Extracting x64/libsupol.so to boot-patcher/arch/amd64/system/lib64/libsupol.so
Found Hackerskeyboard.apk at: update/data/app/Hackerskeyboard.apk
Found Drivedroid.apk at: update/data/app/Drivedroid.apk
Found RouterKeygen.apk at: update/data/app/RouterKeygen.apk
Found USBKeyboard.apk at: update/data/app/USBKeyboard.apk
Found OpenVPN.apk at: update/data/app/OpenVPN.apk
Found cSploit.apk at: update/data/app/cSploit.apk
Found Shodan.apk at: update/data/app/Shodan.apk
Found RFAnalyzer.apk at: update/data/app/RFAnalyzer.apk
Finished downloading all apps
Kernel: Copying common files...
Kernel: Copying armhf arch specific common files...
Kernel: Copying boot-patcher files...
Kernel: Copying armhf arch specific boot-patcher files...
Kernel: Configuring installer script for oneplus1
Kernel: Configuring boot-patcher script for oneplus1
Found kernel image at: devices/marshmallow/oneplus1/zImage
Found DTB image at: devices/marshmallow/oneplus1/dtb.img
NetHunter: Copying common files...
NetHunter: Copying armhf arch specific common files...
NetHunter: Copying update files...
NetHunter: Copying armhf arch specific update files...
NetHunter: Configuring installer script for oneplus1
Creating ZIP file: update-nethunter-oneplus1-marshmallow-nobrand-20160913_212023.zip
  Added: env.sh
  Added: META-INF/com/google/android/update-binary
  Added: META-INF/com/google/android/updater-script
  Added: system/etc/init.d/90userinit
  Added: system/etc/nano/html.nanorc
  Added: system/etc/nano/makefile.nanorc
  Added: system/etc/nano/awk.nanorc
  Added: system/etc/nano/css.nanorc
  Added: system/etc/nano/ruby.nanorc
  Added: system/etc/nano/perl.nanorc
  Added: system/etc/nano/xml.nanorc
  Added: system/etc/nano/tex.nanorc
  Added: system/etc/nano/ocaml.nanorc
  Added: system/etc/nano/objc.nanorc
  Added: system/etc/nano/cmake.nanorc
  Added: system/etc/nano/asm.nanorc
  Added: system/etc/nano/tcl.nanorc
  Added: system/etc/nano/python.nanorc
  Added: system/etc/nano/nanorc.nanorc
  Added: system/etc/nano/patch.nanorc
  Added: system/etc/nano/fortran.nanorc
  Added: system/etc/nano/c.nanorc
  Added: system/etc/nano/php.nanorc
  Added: system/etc/nano/groff.nanorc
  Added: system/etc/nano/java.nanorc
  Added: system/etc/nano/sh.nanorc
  Added: system/etc/nano/nanorc
  Added: system/etc/terminfo/E/Eterm
  Added: system/etc/terminfo/E/Eterm-color
  Added: system/etc/terminfo/a/ansi
  Added: system/etc/terminfo/d/dumb
  Added: system/etc/terminfo/x/xterm-vt220
  Added: system/etc/terminfo/x/xterm
  Added: system/etc/terminfo/x/xterm-r5
  Added: system/etc/terminfo/x/xterm-256color
  Added: system/etc/terminfo/x/xterm-color
  Added: system/etc/terminfo/x/xterm-xfree86
  Added: system/etc/terminfo/x/xterm-r6
  Added: system/etc/terminfo/w/wsvt25
  Added: system/etc/terminfo/w/wsvt25m
  Added: system/etc/terminfo/m/mach-bold
  Added: system/etc/terminfo/m/mach-color
  Added: system/etc/terminfo/m/mach
  Added: system/etc/terminfo/v/vt100
  Added: system/etc/terminfo/v/vt52
  Added: system/etc/terminfo/v/vt102
  Added: system/etc/terminfo/v/vt220
  Added: system/etc/terminfo/h/hurd
  Added: system/etc/terminfo/l/linux
  Added: system/etc/terminfo/p/pcansi
  Added: system/etc/terminfo/c/cygwin
  Added: system/etc/terminfo/c/cons25
  Added: system/etc/terminfo/s/screen-bce
  Added: system/etc/terminfo/s/screen-256color
  Added: system/etc/terminfo/s/screen-256color-bce
  Added: system/etc/terminfo/s/screen
  Added: system/etc/terminfo/s/sun
  Added: system/etc/terminfo/s/screen-s
  Added: system/etc/terminfo/s/screen-w
  Added: system/etc/terminfo/r/rxvt-basic
  Added: system/etc/terminfo/r/rxvt
  Added: system/bin/proxmark3
  Added: system/bin/scripts/test_t55x7_psk.lua
  Added: system/bin/scripts/tnp3sim.lua
  Added: system/bin/scripts/writeraw.lua
  Added: system/bin/scripts/mifare_autopwn.lua
  Added: system/bin/scripts/test.lua
  Added: system/bin/scripts/emul2dump.lua
  Added: system/bin/scripts/14araw.lua
  Added: system/bin/scripts/test_t55x7_fsk.lua
  Added: system/bin/scripts/parameters.lua
  Added: system/bin/scripts/mfkeys.lua
  Added: system/bin/scripts/cmdline.lua
  Added: system/bin/scripts/ndef_dump.lua
  Added: system/bin/scripts/emul2html.lua
  Added: system/bin/scripts/test_t55x7_bi.lua
  Added: system/bin/scripts/tracetest.lua
  Added: system/bin/scripts/dumptoemul.lua
  Added: system/bin/scripts/tnp3dump.lua
  Added: system/bin/scripts/remagic.lua
  Added: system/bin/scripts/test_t55x7_ask.lua
  Added: system/bin/scripts/formatMifare.lua
  Added: system/bin/scripts/hf_read.lua
  Added: system/bin/scripts/htmldump.lua
  Added: system/bin/lualibs/mf_default_keys.lua
  Added: system/bin/lualibs/html_dumplib.lua
  Added: system/bin/lualibs/commands.lua
  Added: system/bin/lualibs/utils.lua
  Added: system/bin/lualibs/getopt.lua
  Added: system/bin/lualibs/htmlskel.lua
  Added: system/bin/lualibs/taglib.lua
  Added: system/bin/lualibs/read14a.lua
  Added: system/bin/lualibs/default_toys.lua
  Added: system/bin/lualibs/hf_reader.lua
  Added: system/lib/libusb.so
  Added: system/lib/libreadline.so
  Added: system/lib/libncurses.so
  Added: system/lib/libtermcap.so
  Added: data/local/kali_chrootinstall_info.txt
  Added: data/local/nhscripts/ath9k_disable.sh
  Added: data/local/nhscripts/ath9k_enable.sh
  Added: data/app/Hackerskeyboard.apk
  Added: data/app/Term-nh.apk
  Added: data/app/OpenVPN.apk
  Added: data/app/cSploit.apk
  Added: data/app/Drivedroid.apk
  Added: data/app/USBKeyboard.apk
  Added: data/app/Shodan.apk
  Added: data/app/RFAnalyzer.apk
  Added: data/app/RouterKeygen.apk
  Added: data/app/BlueNMEA.apk
  Added: data/app/VNC-nh.apk
  Added: data/app/nethunter.apk
  Added: boot-patcher/env.sh
  Added: boot-patcher/boot-patcher.sh
  Added: boot-patcher/zImage
  Added: boot-patcher/dtb.img
  Added: boot-patcher/patch.d-env
  Added: boot-patcher/META-INF/com/google/android/update-binary
  Added: boot-patcher/META-INF/com/google/android/updater-script
  Added: boot-patcher/system/xbin/hid-keyboard
  Added: boot-patcher/system/xbin/supolicy
  Added: boot-patcher/system/etc/firmware/rt2860.bin
  Added: boot-patcher/system/etc/firmware/ar9170-1.fw
  Added: boot-patcher/system/etc/firmware/rt2870.bin
  Added: boot-patcher/system/etc/firmware/rt73.bin
  Added: boot-patcher/system/etc/firmware/ar9170-2.fw
  Added: boot-patcher/system/etc/firmware/htc_9271.fw
  Added: boot-patcher/system/etc/firmware/htc_7010.fw
  Added: boot-patcher/system/etc/firmware/rt2561.bin
  Added: boot-patcher/system/etc/firmware/carl9170-1.fw
  Added: boot-patcher/system/etc/firmware/rt3070.bin
  Added: boot-patcher/system/etc/firmware/zd1211/zd1211b_uphm
  Added: boot-patcher/system/etc/firmware/zd1211/zd1211_uphr
  Added: boot-patcher/system/etc/firmware/zd1211/zd1211_ub
  Added: boot-patcher/system/etc/firmware/zd1211/zd1211b_uphr
  Added: boot-patcher/system/etc/firmware/zd1211/zd1211b_uph
  Added: boot-patcher/system/etc/firmware/zd1211/zd1211_uphm
  Added: boot-patcher/system/etc/firmware/zd1211/zd1211b_ur
  Added: boot-patcher/system/etc/firmware/zd1211/zd1211_uph
  Added: boot-patcher/system/etc/firmware/zd1211/zd1211_ur
  Added: boot-patcher/system/etc/firmware/zd1211/zd1211b_ub
  Added: boot-patcher/system/etc/firmware/rtlwifi/rtl8192cufw.bin
  Added: boot-patcher/system/etc/firmware/rtlwifi/rtl8188efw.bin
  Added: boot-patcher/system/lib/libsupol.so
  Added: boot-patcher/patch.d/03-no-verity-opt-encrypt
  Added: boot-patcher/patch.d/02-supersu
  Added: boot-patcher/patch.d/01-ramdisk-patch
  Added: boot-patcher/tools/mkbootimg
  Added: boot-patcher/tools/lz4
  Added: boot-patcher/tools/unpackbootimg
  Added: boot-patcher/ramdisk-patch/init.nethunter.rc
  Added: boot-patcher/ramdisk-patch/sbin/hostapd
  Added: boot-patcher/ramdisk-patch/sbin/dvmediarevert
  Added: boot-patcher/ramdisk-patch/sbin/media_profiles.xml
  Added: boot-patcher/ramdisk-patch/sbin/dvbootscript.sh
  Added: boot-patcher/ramdisk-patch/sbin/ath9k_disable.sh
  Added: boot-patcher/ramdisk-patch/sbin/ath9k_enable.sh
  Added: boot-patcher/ramdisk-patch/sbin/busybox_nh
  Added: arch/amd64/system/bin/proxmark3
  Added: arch/amd64/system/lib64/libusb.so
  Added: arch/amd64/system/lib64/libreadline.so
  Added: arch/amd64/system/lib64/libncurses.so
  Added: arch/amd64/system/lib64/libtermcap.so
  Added: arch/amd64/tools/screenres
  Added: arch/amd64/tools/busybox
  Added: arch/arm64/system/bin/proxmark3
  Added: arch/arm64/system/lib64/libusb.so
  Added: arch/arm64/system/lib64/libreadline.so
  Added: arch/arm64/system/lib64/libncurses.so
  Added: arch/arm64/system/lib64/libtermcap.so
  Added: arch/arm64/tools/screenres
  Added: arch/arm64/tools/busybox
  Added: arch/i386/system/bin/proxmark3
  Added: arch/i386/system/lib/libusb.so
  Added: arch/i386/system/lib/libreadline.so
  Added: arch/i386/system/lib/libncurses.so
  Added: arch/i386/system/lib/libtermcap.so
  Added: arch/i386/tools/screenres
  Added: arch/i386/tools/busybox
  Added: arch/armhf/system/bin/proxmark3
  Added: arch/armhf/system/lib/libusb.so
  Added: arch/armhf/system/lib/libreadline.so
  Added: arch/armhf/system/lib/libncurses.so
  Added: arch/armhf/system/lib/libtermcap.so
  Added: arch/armhf/tools/screenres
  Added: arch/armhf/tools/busybox
  Added: tools/previnstall.sh
  Added: tools/installsu.sh
  Added: tools/screenres
  Added: tools/installchroot.sh
  Added: tools/installbusybox.sh
  Added: tools/busybox
Created NetHunter installer: update-nethunter-oneplus1-marshmallow-nobrand-20160913_212023.zip
```
but also playing with parameters doesn't change this
all i can report is i need to add my modification to make it do what it should.

**Comment by jcadduono** [comment]
Right, so you would put your scripts in `devicename/ramdisk-patch/sbin/your script.sh`

and you're 100% sure your build.py is exactly the one from current master?

**Comment by zanezam** [comment]
aye will put the scripts in there then, thx.
and yup im 100% sure that i am using the one from actual master branch
i even did a fresh clone for testing. anyway if u or anyone else can't reproduce that
i guess some strange thing is happening here on my side. will also try some other 
distros (kali incl.) when i have time. this is so strange i just have to find out now :-)

**Comment by zanezam** [comment]
back again with convincement that there must be an issue with the "IgnoredFiles loop" as i did:
freshly install kali
freshly cloned kali-nethunter
checked if i have master checkout (default after clone as always)
did this again ./build.py -d oneplus1 -m -nk -ns -nb -nf
and got again "arch" directory included in the zip instead of excluded
so this is system nr. 3 (and the one u also use?) were that happend
btw: Python 2.7.12+ (default, Aug  4 2016, 20:04:34)
anyway to not unnecessarily strech out this topic here i will push my loop modification again in my custom banch on top of the actual merged modified version from your latest commit. if there is a need for it on mater branch u know were u can get it.

to underline that there might be a problem here another example were and why that can happen:
http://stackoverflow.com/questions/5864166/return-statement-in-for-loops

**Comment by jcadduono** [comment]
solved it, it's because removing subdir from array causes a shift that makes it pass the next one in the subdir array, excluding it from the check....coming up with a fix

**Comment by jcadduono** [comment]
https://github.com/offensive-security/kali-nethunter/commit/6ada1dbb084e0e26176701470e7b0c74cbf8aec9

**Comment by zanezam** [comment]
Great indeed that does fix it thx!

**Pull request closed without merging**
