### PR TITLE
Merge changes

### PR DESCRIPTION
**Pull request by kimocoder**
* Updated SuperSU (to v2.82 SR5)
   -- suinit: Fix (flashed) TWRP 3.1.1 compatibility on Pixel (XL)
   -- FBE: allow FBE devices to boot unencrypted (unless KEEPFORCEENCRYPT is set)

* Updated Term-nh (terminal emulator)
   -- Fixed foreground being killed, keep the code updated
   -- Updated gradle and other Android build libs

* Added "Walrus", an APK for NFC cloning (read/write)

* Fixed 2 indents in 2 files

### CODE REVIEW

**Comment by kimocoder** [comment]
About the files not being available in "adb shell" but only locally, I actually managed to fix it when building a brand new kernel for Nexus 6P (angler) based on Android 8.1 with jcadduono's source + merged all from upstream v3.20 (old was 3.10).

tested and working, with all modules in place. merging into devices.

**Comment by kimocoder** [comment]
@yesimxev I found the problem. The Term-NH package wasn't signed. Removing for now, pushed the changes to @binkybear as he's the one in charge of it anyway.

**Comment by kimocoder** [comment]
Changed back. This update should be merged as in contains an update of SuperSu.
@Re4son it's ready. Pushed the Term-nh.apk updates to @binkybear so he should fix it when he's available.

**Comment by Re4son** [comment]
Do you want to create a signed apk yourself? We'll only sideload it so doesn't have to be signed by a particular person.

**Comment by kimocoder** [comment]
I'll fix the Term-NH also, just gimme some more time :+1:

**Comment by Re4son** [comment]
good to go?
I'll merge it into 2019.2 for testing, ok?

**Comment by kimocoder** [comment]
Jepp. Should be straight forward this one 🙂

**Pull request merged**
