### PR TITLE
New device: Sony Xperia Z Ultra (togari) support

### PR DESCRIPTION
**Pull request by vovanx500**

### CODE REVIEW

**Comment by jcadduono** [comment]
If you don't mind cleaning up some extra blank lines and squashing your work down into 1 commit that would be helpful. You will probably want to close your other pull request, or merge this one onto that and close this one instead.

New devices should come as a single commit, with the commit message header following a specific format, ex.
[Xperia Z Ultra] Add device support for togari on lollipop

**Comment by vovanx500** [comment]
I am really sorry for the mess, but is it possible to fix on a website, as due to my slow internet it would be a bit problematic to download whole git repository?

**Comment by jcadduono** [comment]
the bolded item is actually the branch, which in your case is currently called "master"
ideally, you would rename the branch to something like "android-5.1"
you can rename branches locally and then push them to github.

to fix up your commits:
git clone https://vovanx500@github.com/vovanx500/kali-nethunter.git -b master
cd kali-nethunter
git rebase -i HEAD~6
change "pick" to "f" on all commits that came after your initial change
change your initial change's "pick" to "r" so you can edit the commit message
then git push -u origin master -f
you can also do:
git remote add upstream https://vovanx500@github.com/offensive-security/kali-nethunter.git
if we make any commits on top of what we have, you can simply
git rebase upstream master
and it will automatically bring you up to the latest, retaining your changes :)

**Comment by jcadduono** [comment]
re-open at nethunter-devices repository when you are ready (see readme of nethunter-installer)

**Pull request closed without merging**
